/* Context actions */
export const SET_LOGIN_CONTEXT = 'SET_LOGIN_CONTEXT';
export const SET_LOGOUT_CONTEXT = 'SET_LOGIN_CONTEXT';
export const SET_CURRENT_COMPONENT = 'SET_CURRENT_COMPONENT';
export const HANDLE_CALENDAR_SEARCH_CHANGE = 'HANDLE_CALENDAR_SEARCH_CHANGE';
export const HANDLE_NOTIFICACIONES_SEARCH_CHANGE = 'HANDLE_NOTIFICACIONES_SEARCH_CHANGE';
export const HANDLE_MENSAJES_SEARCH_CHANGE = 'HANDLE_MENSAJES_SEARCH_CHANGE';
export const HANDLE_CALENDARIO_FILTRO_CHANGE= 'HANDLE_CALENDARIO_FILTRO_CHANGE';
export const SET_SELECTED_ESTUDIANTE = 'SET_SELECTED_ESTUDIANTE';

/* Platform actions */
export const SET_PLATFORM = 'SET_PLATFORM';

/* Data actions */
export const MERGE_INASISTENCIAS = 'MERGE_INASISTENCIAS';
export const MERGE_CALIFICACIONES = 'MERGE_CALIFICACIONES';
export const MERGE_MENSAJES = 'MERGE_MENSAJES';
export const MERGE_MENSAJE_COMENTARIOS = 'MERGE_MENSAJE_COMENTARIOS';
export const MERGE_NOTIFICACIONES = 'MERGE_NOTIFICACIONES';
export const MERGE_TAREAS = 'MERGE_TAREAS';
export const MERGE_TAREA_COMENTARIOS = 'MERGE_TAREA_COMENTARIOS';
export const MERGE_TIPOS_TAREAS = 'MERGE_TIPOS_TAREAS';
export const MERGE_ESTUDIANTES = 'MERGE_ESTUDIANTES';
export const MERGE_PROFILES = 'MERGE_PROFILES';
